### PR TITLE
.netcore 2 preview 2

### PR DESCRIPTION
**Pull request by MathiasKowoll**
Just added a working version for .net core 2 preview 2

### CODE REVIEW

**Comment by nabinked** [comment]
Thank for the pull request. I will review and merge it later this evening. Cheers (y)

**Comment by nabinked** [comment]
I have made some changes and made the library support netstandard2.0 which can be referenced by netcoreapp2.0 apps. Since its a breaking change I have bumped the Nuget version to 3.0.0. So It should be all good now. Can you double check and confirm. Thanks :)

**Comment by MathiasKowoll** [comment]
Sure will, once it is available to download from nugget.

**Comment by nabinked** [comment]
Sorry I forgot to push the release version. It should be up on Nuget now.

**Comment by MathiasKowoll** [comment]
Just tested and it is working great, 

Thx

**Comment by nabinked** [comment]
Great (y)

**Pull request merged**
