### PR TITLE
Add default message and title options

### PR DESCRIPTION
**Pull request by os1r1s110**
This lets the user specify his default titles and messages for the various notification types.

### CODE REVIEW

**Comment by os1r1s110** [comment]
Related to PR #7 , see in the comments section.

**Comment by nabinked** [comment]
Thanks @os1r1s110. I will have a look.

**Comment by os1r1s110** [comment]
No problem, feel free to modify it if you think there is a better alternative :)

**Comment by nabinked** [comment]
I have merged your commits along with my modifications and few changes into the dev branch of this repo. I will merge it with the master branch if all is good. And also, I think it will  be better if you can make pull-requests on to the dev branch instead of the master branch so that when all is done we can safely merge to the master branch.

**Comment by nabinked** [comment]
Merged to master and published to Nuget. Version 2.0.2

**Comment by os1r1s110** [comment]
Ok, I'll try to make the next PR on the Dev branch, I thought it was not created (but I was mistaken by the fact that it was the case on another repo I'm working on ahaha)

**Comment by nabinked** [comment]
Yeah now I have made the dev branch as the default branch so any new PR should come to Dev branch by default.

**Pull request merged**
