### PR TITLE
UTF-8 characters in AJAX request

### PR DESCRIPTION
**Pull request by dkolarev**
When using UTF-8 characters in AJAX request toastr I got exception. The reason was that non-ASCII characters are not allowed in HTTP response headers.

The solution is to add message encoding in

_NtoastNotifyAjaxToastsMiddleware.cs_ in line `httpContext.Response.Headers.Add(Constants.ResponseHeaderKey, WebUtility.UrlEncode(messagesJson));`

and decoding in _NToastNotify.ts_

This is for issue #61 and #37

### CODE REVIEW

**Comment by nabinked** [comment]
Great stuff man. I will try to merge this in tonight. Thanks. Much appreciated and sorry I have not been able to pay much attention to this repo

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
बाट: Davor Kolarević <notifications@github.com>
पठाइयो: Thursday, March 21, 2019 1:51:27 AM
प्रापक: nabinked/NToastNotify
बोधार्थ: Subscribed
विषय: [nabinked/NToastNotify] When using UTF-8 characters in AJAX request toastr I got exception. T… (#62)


…he reason was that non-ASCII characters are not allowed in HTTP response headers.

The solution is to add message encoding in

NtoastNotifyAjaxToastsMiddleware.cs in line httpContext.Response.Headers.Add(Constants.ResponseHeaderKey, WebUtility.UrlEncode(messagesJson));

and decoding in NToastNotify.ts

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/nabinked/NToastNotify/pull/62<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnabinked%2FNToastNotify%2Fpull%2F62&data=02%7C01%7C%7C930ef109b3b54779da3e08d6ad438825%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636886902890810147&sdata=7xK7IWO%2BEfuZ%2BXWEBRrb%2By8qIcRsSO3p%2F1dopKglwik%3D&reserved=0>

Commit Summary

  *   When using UTF-8 characters in AJAX request toastr I got exception. The reason was that non-ASCII characters are not allowed in HTTP response headers.

File Changes

  *   M src/Js/dist/noty.js<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnabinked%2FNToastNotify%2Fpull%2F62%2Ffiles%23diff-0&data=02%7C01%7C%7C930ef109b3b54779da3e08d6ad438825%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636886902890820158&sdata=AkkP2JkHKAqZV27mKDokHsUOJUeKnut2oDl2ybanj9Q%3D&reserved=0> (2)
  *   M src/Js/dist/toastr.js<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnabinked%2FNToastNotify%2Fpull%2F62%2Ffiles%23diff-1&data=02%7C01%7C%7C930ef109b3b54779da3e08d6ad438825%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636886902890830163&sdata=2yitiH3NZnJR66O4IcDj2LYq6h5HJQeXpQUtOTStgx0%3D&reserved=0> (2)
  *   M src/Js/src/NToastNotify.ts<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnabinked%2FNToastNotify%2Fpull%2F62%2Ffiles%23diff-2&data=02%7C01%7C%7C930ef109b3b54779da3e08d6ad438825%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636886902890840174&sdata=BBesR0PGVZpgOWyBwXxNCSl2EkCViN1nv5rqQndTYGg%3D&reserved=0> (7)
  *   M src/NtoastNotifyAjaxToastsMiddleware.cs<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnabinked%2FNToastNotify%2Fpull%2F62%2Ffiles%23diff-3&data=02%7C01%7C%7C930ef109b3b54779da3e08d6ad438825%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636886902890850185&sdata=QqOsTQ3%2BLMI23Qg6cXKp90hnvAYL6hdFq5wFYH0BdEo%3D&reserved=0> (3)

Patch Links:

  *   https://github.com/nabinked/NToastNotify/pull/62.patch<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnabinked%2FNToastNotify%2Fpull%2F62.patch&data=02%7C01%7C%7C930ef109b3b54779da3e08d6ad438825%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636886902890860190&sdata=Y6zKS8mhtoSrrUSjrKlA6nLO3Yu7ijcxnDngN0ol74c%3D&reserved=0>
  *   https://github.com/nabinked/NToastNotify/pull/62.diff<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnabinked%2FNToastNotify%2Fpull%2F62.diff&data=02%7C01%7C%7C930ef109b3b54779da3e08d6ad438825%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636886902890870207&sdata=ijz61nVAk9%2B30YRfX5UQRg72rXmJh2JJRZ%2FUXmuaZP8%3D&reserved=0>

**Comment by nabinked** [comment]
Will push a release to nuget later

**Comment by dkolarev** [comment]
Thanks @nabinked I appreciate that. I will really need nuget package soon.

**Comment by nabinked** [comment]
new versoin is up already

**Pull request merged**
